### PR TITLE
getAuthenticationContext: add tests, check for valid token

### LINKED ISSUE #42: getAuthenticationContext

### PR DESCRIPTION
**Pull request by rkillackey**
Resolves #42

### CODE REVIEW

**Comment by rkillackey** [comment]
@dpikt Actually I think `getAuthenticationContext` should return `undefined` if the token is invalid (even if context exists), non?

**Comment by dpikt** [comment]
@rkillackey agreed!

**Comment by rkillackey** [comment]
@dpikt Updated!

**Comment by dpikt** [comment]
Remember to bump version before merging :)

**Comment by dpikt** [comment]
@rkillackey got the build to run. Look at that test coverage! 🙌

**Comment by rkillackey** [comment]
@dpikt haha yeah i just restarted it. Beautiful!

**Pull request merged**
