### PR TITLE
Allow case where no actions are specified

### PR DESCRIPTION
**Pull request by dpikt**

### CODE REVIEW

**Comment by davemcorwin** [comment]
why?

**Comment by dpikt** [comment]
Lol good question- in case you want to send a request without dispatching any actions. Not the most common use case, but I figured it shouldn't throw a destructuring error if it happens.

**Comment by davemcorwin** [comment]
Its a 'required' argument, so if you want to throw a more meaningful error if its not provided or all three aren't specified that works for me. However, this shouldn't support making an api request without actions to dispatch. The library exposes both the `api` and `http` modules for making plain ol api requests.

**Comment by dpikt** [comment]
Fair enough, I'll change it to throw a better error.

**Pull request closed without merging**
